# Generated by Django 4.2.27 on 2026-03-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Категория новости', 'verbose_name_plural': 'Категории новостей'},
        ),
    ]
