# Generated by Django 4.2.27 on 2026-03-24 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_newscategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.newscategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание (кырг.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Горячая новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_kg',
            field=models.TextField(blank=True, verbose_name='Краткое описание (кырг.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(blank=True, verbose_name='Краткое описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='Заголовок (кырг.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
