# Generated by Django 4.2.27 on 2026-03-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sight',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Достопримечательность', 'verbose_name_plural': 'Достопримечательности'},
        ),
        migrations.AlterModelOptions(
            name='sightimage',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Изображение достопримечательности', 'verbose_name_plural': 'Изображения достопримечательностей'},
        ),
    ]
