# Generated by Django 4.2.27 on 2026-03-24 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_alter_sight_options_alter_sightimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание (кырг.)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='main_image',
            field=models.ImageField(upload_to='sights/main/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='short_description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='short_description_kg',
            field=models.TextField(blank=True, verbose_name='Краткое описание (кырг.)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='short_description_ru',
            field=models.TextField(blank=True, verbose_name='Краткое описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='sightimage',
            name='image',
            field=models.ImageField(upload_to='sights/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sightimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='sightimage',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='sights.sight', verbose_name='Достопримечательность'),
        ),
        migrations.AlterField(
            model_name='sightimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='sightimage',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='sightimage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (рус.)'),
        ),
    ]
