# Generated by Django 4.2.27 on 2026-03-24 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_kg', models.CharField(max_length=255)),
                ('position_ru', models.CharField(max_length=255)),
                ('position_en', models.CharField(max_length=255)),
                ('position_kg', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='office/leadership/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership Member',
                'verbose_name_plural': 'Leadership Members',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('regulations', 'Regulations'), ('orders', 'Orders'), ('reports', 'Reports')], max_length=20)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_kg', models.CharField(max_length=255)),
                ('file_ru', models.FileField(upload_to='office/documents/ru/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_en', models.FileField(upload_to='office/documents/en/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_kg', models.FileField(upload_to='office/documents/kg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Official Document',
                'verbose_name_plural': 'Official Documents',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('procurement', 'State Procurement'), ('tender', 'Tender')], max_length=20)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_kg', models.CharField(max_length=255)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_kg', models.TextField()),
                ('amount_som', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deadline', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procurement Item',
                'verbose_name_plural': 'Procurement Items',
                'ordering': ('order', 'deadline', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('investment', 'Investment Project'), ('state', 'State Program')], max_length=20)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_kg', models.CharField(max_length=255)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_kg', models.TextField()),
                ('implementation_period_ru', models.CharField(max_length=255)),
                ('implementation_period_en', models.CharField(max_length=255)),
                ('implementation_period_kg', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='office/projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('order', 'id'),
            },
        ),
    ]
