# Generated by Django 4.2.27 on 2026-03-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadershipmember',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководство'},
        ),
        migrations.AlterModelOptions(
            name='officialdocument',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Официальный документ', 'verbose_name_plural': 'Официальные документы'},
        ),
        migrations.AlterModelOptions(
            name='procurementitem',
            options={'ordering': ('order', 'deadline', 'id'), 'verbose_name': 'Закупка или тендер', 'verbose_name_plural': 'Закупки и тендеры'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Проект или программа', 'verbose_name_plural': 'Проекты и программы'},
        ),
    ]
