# Generated by Django 4.2.27 on 2026-03-24 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_content', '0002_alter_leadershipmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipmember',
            name='full_name_en',
            field=models.CharField(max_length=255, verbose_name='ФИО (англ.)'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='full_name_kg',
            field=models.CharField(max_length=255, verbose_name='ФИО (кырг.)'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='full_name_ru',
            field=models.CharField(max_length=255, verbose_name='ФИО (рус.)'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='photo',
            field=models.ImageField(upload_to='office/leadership/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='position_en',
            field=models.CharField(max_length=255, verbose_name='Должность (англ.)'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='position_kg',
            field=models.CharField(max_length=255, verbose_name='Должность (кырг.)'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='position_ru',
            field=models.CharField(max_length=255, verbose_name='Должность (рус.)'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='category',
            field=models.CharField(choices=[('regulations', 'Нормативные акты'), ('orders', 'Распоряжения'), ('reports', 'Отчёты')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='file_en',
            field=models.FileField(upload_to='office/documents/en/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF (англ.)'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='file_kg',
            field=models.FileField(upload_to='office/documents/kg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF (кырг.)'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='file_ru',
            field=models.FileField(upload_to='office/documents/ru/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF (рус.)'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='amount_som',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма (сом)'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='deadline',
            field=models.DateField(verbose_name='Крайний срок'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='description_en',
            field=models.TextField(verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='description_kg',
            field=models.TextField(verbose_name='Описание (кырг.)'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='description_ru',
            field=models.TextField(verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='type',
            field=models.CharField(choices=[('procurement', 'Государственная закупка'), ('tender', 'Тендер')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_kg',
            field=models.TextField(verbose_name='Описание (кырг.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=models.TextField(verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='office/projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_period_en',
            field=models.CharField(max_length=255, verbose_name='Период реализации (англ.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_period_kg',
            field=models.CharField(max_length=255, verbose_name='Период реализации (кырг.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_period_ru',
            field=models.CharField(max_length=255, verbose_name='Период реализации (рус.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('investment', 'Инвестиционный проект'), ('state', 'Государственная программа')], max_length=20, verbose_name='Тип'),
        ),
    ]
