# Generated by Django 4.2.27 on 2026-04-28 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_content', '0003_alter_leadershipmember_full_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='ФИО (рус.)')),
                ('full_name_en', models.CharField(max_length=255, verbose_name='ФИО (англ.)')),
                ('full_name_kg', models.CharField(max_length=255, verbose_name='ФИО (кырг.)')),
                ('position_ru', models.CharField(max_length=255, verbose_name='Должность (рус.)')),
                ('position_en', models.CharField(max_length=255, verbose_name='Должность (англ.)')),
                ('position_kg', models.CharField(max_length=255, verbose_name='Должность (кырг.)')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                (
                    'photo',
                    models.ImageField(
                        upload_to='office/employees/',
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])],
                        verbose_name='Фотография',
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('order', 'id'),
            },
        ),
    ]
