# Generated by Django 4.2.27 on 2026-03-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='departmentcategory',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Категория подразделения', 'verbose_name_plural': 'Категории подразделений'},
        ),
        migrations.AlterModelOptions(
            name='departmentleader',
            options={'verbose_name': 'Руководитель подразделения', 'verbose_name_plural': 'Руководители подразделений'},
        ),
    ]
