# Generated by Django 4.2.27 on 2026-03-24 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='departments.departmentcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.FileField(upload_to='departments/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_description_kg',
            field=models.TextField(blank=True, verbose_name='Краткое описание (кырг.)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_description_ru',
            field=models.TextField(blank=True, verbose_name='Краткое описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='departmentcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='departmentcategory',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='departmentcategory',
            name='name_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='departmentcategory',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='departmentcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='departmentcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (англ.)'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='address_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (кырг.)'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (рус.)'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='departments.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='photo',
            field=models.ImageField(upload_to='departments/leaders/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='position_en',
            field=models.CharField(max_length=255, verbose_name='Должность (англ.)'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='position_kg',
            field=models.CharField(max_length=255, verbose_name='Должность (кырг.)'),
        ),
        migrations.AlterField(
            model_name='departmentleader',
            name='position_ru',
            field=models.CharField(max_length=255, verbose_name='Должность (рус.)'),
        ),
    ]
