# Generated by Django 4.2.27 on 2026-03-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacategory',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Категория медиа', 'verbose_name_plural': 'Категории медиа'},
        ),
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ('order', '-created_at', '-id'), 'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медиафайлы'},
        ),
    ]
