# Generated by Django 4.2.27 on 2026-03-24 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_mediacategory_options_alter_mediaitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='name_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='media.mediacategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(upload_to='media/items/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], max_length=10, verbose_name='Тип'),
        ),
    ]
